version: '3'
services:
  php-apache-dev:
    image: 'webdevops/php-apache-dev:8.2'
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'mysql:db'
    depends_on: []
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - './php:/app'
    working_dir: /app
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=demo1234
    ports:
      - '3360:3306'
    volumes:
      - './mysql:/var/lib/mysql'
    image: 'mysql:8.1.0'
